services:
  nginx:
    container_name: nginx
    image: nginx
    networks: 
      - inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - "WordPress:/var/www/html"
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: on-failure

  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - "mariadb:/var/lib/mysql"
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - "WordPress:/var/www/html"
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: on-failure

  redis:
    container_name: redis
    build: ./requirements/bonus/redis/.
    image: redis
    volumes:
      - "WordPress:/var/www/html"
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  adminer:
    container_name: adminer
    image: adminer
    networks:
      - inception
    build: ./requirements/bonus/adminer
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    restart: on-failure

  ftp:
    container_name: ftp
    image: ftp
    networks:
      - inception
    build: ./requirements/bonus/FTP
    ports:
      - "40000-40005:40000-40005"
      - "21:21"
      - "20:20"
    volumes:
      - "WordPress:/home/${FTP_USER}/ftp"
    depends_on:
      - wordpress
    env_file: ./.env
    restart: on-failure

  node-js:
    container_name: node-js
    image: node_js
    build: ./requirements/bonus/node
    networks:
      - inception
    ports:
      - "1337:1337"
    depends_on:
      - mariadb
      - wordpress
    env_file: ./.env
    restart: on-failure

  cadvisor:
    container_name: cadvisor
    image: cadvisor
    build: ./requirements/bonus/cadvisor
    ports:
      - "8000:8080"
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: "/home/youssef/data/mariadb/"
      o: bind
  WordPress:
    driver: local
    driver_opts:
      type: none
      device: "/home/youssef/data/wordpress/"
      o: bind

